backend:
  name: github
  branch: master
  repo: comerc/pro-gatsby-2
media_folder: static/img
public_folder: /img
collections:
  - name: team
    label: Team
    folder: src/team
    create: true
    slug: '{{slug}}'
    fields:
      - { label: Team Member, name: title, widget: string }
      - { label: Bio, name: bio, widget: markdown }
      - { label: Body, name: body, widget: markdown }
